<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
  <!-- <h1>Zend Framework &amp; Capistrano</h1> -->
  <h1>大嶋さんの部屋</h1>

  <br/>

  <div class='row'>
    <div class='offset3 span6'>
  <img src='http://www.rubyinside.com/wp-content/uploads/2007/06/capistrano-logo-small.png' />
  <img src='http://www.phpro.be/sites/default/files/pictures/zend-framework.png' />
    </div>
  </div>
</div>

<!-- Example row of columns -->
<div class="row">
  <div class="span6">
    <h2>Initialize</h2>
    <pre class='prettyprint lang-sh'>cap production deploy:<b>setup</b></pre>
  </div>
  <div class="span6">
    <h2>Deploy latest code</h2>
    <pre class='prettyprint lang-sh'>cap production deploy</pre>
  </div>

  <div class="span6">
    <h2>Rollback source code</h2>
    <pre class='prettyprint lang-sh'>cap production deploy:<b>rollback</b></pre>
 </div>

  <div class="span6">
    <h2>Restart all servers</h2>
    <pre class='prettyprint lang-sh'>cap production deploy:<b>restart</b></pre>
  </div>

  <div class="span6">
    <h2>Deploy to a specific server</h2>
    <pre class='prettyprint lang-sh'>cap production deploy <b>HOSTS</b>=target_server</pre>
  </div>

  <div class="span6">
    <h2>Switch to maintenance</h2>
    <pre class='prettyprint lang-sh'>cap production deploy:<b>web:disable</b></pre>
  </div>

  <div class="span6">
    <h2>Multiple environments</h2>
    <pre class='prettyprint lang-sh'>cap <b>staging</b> deploy</pre>
  </div>

  <div class="span6">
    <h2>Remove old releases</h2>
    <pre class='prettyprint lang-sh'>cap production deploy:<b>cleanup</b></pre>
  </div>

  <div class='offset1 span10' style='padding-top:20px; padding-bottom:20px;'>
    <a class="btn btn-primary btn-large"
      href='javascript:void(0)'
      onclick='alert("ggrks(ググレカス)")'
      style='width:100%;'>Learn more ...</a>
  </div>
</div>
