<div class="hero-unit">
  <h1>Setup Servers</h1>

  <br/>

  <h3>シェルスクリプトを利用したサーバーのセットアップ</h3>
  <pre class='prettyprint lang-sh'>
# rootで実行
curl -L "http://example.com/setup.sh" | bash</pre>

  <br/>

  <h3>http://example.com/setup.sh</h3>
  <pre class='prettyprint lang-sh'>
#!/bin/sh

# RPMパッケージを追加（Rubyのコンパイル等で使用）
#sudo yum -y groupinstall "Additional Development" "Development tools"
sudo yum -y groupinstall "Development tools"
sudo yum -y install 'openssl-devel' 'zlib-devel' 'pcre-devel' 'readline-devel'

# Zend Framework用のレポジトリ定義を追加
cat &lt;&lt;EOS &gt; /etc/yum.repos.d/zend.repo
[Zend]
name=Zend Server
baseurl=http://repos.zend.com/zend-server/rpm/\$basearch
enabled=1
gpgcheck=1
gpgkey=http://repos.zend.com/zend.key

[Zend_noarch]
name=Zend Server - noarch
baseurl=http://repos.zend.com/zend-server/rpm/noarch
enabled=1
gpgcheck=1
gpgkey=http://repos.zend.com/zend.key
EOS

yum -y install zend-server-php-5.3

# ユーザーの追加
# ※パスワードは変えてね！
useradd geek
echo 'geekgeek' | passwd geek --stdin
mkdir /home/geek/.ssh
chown geek. /home/geek/.ssh
chmod 600 /home/geek/.ssh

# デプロイ先のディレクトリを作成
mkdir /deploy
chown geek /deploy</pre>

  <br/>

  <h3>/etc/httpd/conf/httpd.conf</h3>
  <pre class='prettyprint'>
...(略)...
#ZEND-{すうじ}
#Include "/usr/local/zend/etc/sites.d/globals-*.conf"
#Include "/usr/local/zend/etc/sites.d/vhost_*.conf"
##ZEND-{すうじ}

&lt;VirtualHost *:80&gt;
  # アクセスするドメイン名
  ServerName zf-cap-test.npi.jp

  # Capistranoによるデプロイ先 + /public
  DocumentRoot /deploy/geek_app/current/public

  # Zend Frameworkのステージ定義
  SetEnv APPLICATION_ENV "development"

  # メンテナンスページ用設定
  ErrorDocument 503 /system/maintenance.html
  RewriteEngine On
  RewriteCond %{REQUEST_URI} !.(css|gif|jpg|png)$
  RewriteCond %{DOCUMENT_ROOT}/system/maintenance.html -f
  RewriteCond %{SCRIPT_FILENAME} !maintenance.html
  RewriteRule ^.*$  -  [redirect=503,last]

  # Zend Framework用
  &lt;Directory /deploy/geek_app/current/public&gt;
    DirectoryIndex index.php
    AllowOverride All
    Order allow,deny
    Allow from all
  &lt;/Directory&gt;
&lt;/VirtualHost&gt;</pre>

  <br/>

  <h3>Apacheの起動</h3>
  <pre class='prettyprint lang-sh'>
# rootで実行

# 設定ファイルのチェック
service httpd configtest

# 起動
service httpd start

# 二回目以降は再起動
service httpd graceful</pre>
</div>
